version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "karton_ssl_checks"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "karton_sqlmap"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "xss_scanner"
    schedule:
      interval: "weekly"
