version: "3"

services:
  karton-dns_reaper:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_dns_reaper/Dockerfile
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]
    depends_on: [karton-logger, redis]
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_dns_reaper"

  karton-sqlmap:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_sqlmap/Dockerfile
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]
    depends_on: [karton-logger, redis]
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_sqlmap"

  karton-ssl_checks:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_ssl_checks/Dockerfile
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]
    depends_on: [karton-logger, redis]
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_ssl_checks"

  karton-humble:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_humble/Dockerfile
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]
    depends_on: [karton-logger, redis]
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_humble"

  autoreporter:
    volumes:
      - ./Artemis-modules-extra/extra_modules_config.py:/opt/extra_modules_config.py
      - ./Artemis-modules-extra/autoreporter_addons/ssl_checks/:/opt/artemis/reporting/modules/ssl_checks/
      - ./Artemis-modules-extra/autoreporter_addons/sqlmap/:/opt/artemis/reporting/modules/sqlmap/
      - ./Artemis-modules-extra/autoreporter_addons/dns_reaper/:/opt/artemis/reporting/modules/dns_reaper/
      - ./Artemis-modules-extra/autoreporter_addons/humble/:/opt/artemis/reporting/modules/humble/
