services:
  postgres-test:
    image: postgres
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_DB: artemis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  test-sqlmap:
    build:
      context: .
      dockerfile: karton_sqlmap/Dockerfile
    command: python -m unittest discover
    env_file: env.test

  test-ssl_checks:
    build:
      context: .
      dockerfile: karton_ssl_checks/Dockerfile
    command: python -m unittest discover
    env_file: env.test

  test-redis:
    image: redis:7.0.5

  test-service-with-sql-injection-mysql:
    build: test/images/php-mysql
    volumes:
      - ./test/data/sql_injection_mysql/:/var/www/html/

  test-service-with-sql-injection-mysql-db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root

  test-service-with-sql-injection-mysql-clean-urls:
    build: test/images/php-mysql
    volumes:
      - ./test/data/sql_injection_mysql_clean_urls/:/var/www/html/

  test-service-with-sql-injection-mysql-clean-urls-db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root

  test-service-with-sql-injection-postgres:
    build: test/images/php-postgres
    volumes:
      - ./test/data/sql_injection_postgres/:/var/www/html/

  test-service-with-sql-injection-postgres-db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
