version: "3"

services:
  karton-dns_reaper:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_dns_reaper/Dockerfile
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini"]
    depends_on: [karton-logger, redis]
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_dns_reaper"

  karton-sqlmap:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_sqlmap/Dockerfile
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini"]
    depends_on: [karton-logger, redis]
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_sqlmap"

  karton-ssl_checks:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_ssl_checks/Dockerfile
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini"]
    depends_on: [karton-logger, redis]
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_ssl_checks"
