services:
  karton-dns_reaper:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_dns_reaper/Dockerfile
    volumes:
      - "./docker/karton.ini:/etc/karton/karton.ini"
      - "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_dns_reaper"

  karton-forti_vuln:
    build:
      context: Artemis-modules-extra
      dockerfile: forti_vuln/Dockerfile
    volumes:
      - "./docker/karton.ini:/etc/karton/karton.ini"
      - "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.forti_vuln"

  karton-moodle_scanner:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_moodle_scanner/Dockerfile
    volumes:
      - "./docker/karton.ini:/etc/karton/karton.ini"
      - "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.moodle_scanner"

  karton-sqlmap:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_sqlmap/Dockerfile
    volumes:
      - "./docker/karton.ini:/etc/karton/karton.ini"
      - "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_sqlmap"

  karton-ssl_checks:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_ssl_checks/Dockerfile
    volumes:
      - "./docker/karton.ini:/etc/karton/karton.ini"
      - "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_ssl_checks"
    profiles: [not-arm]

  karton-whatvpn:
    build:
      context: Artemis-modules-extra
      dockerfile: karton_whatvpn/Dockerfile
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.karton_whatvpn"
  
  xss_scanner:
    build:
      context: Artemis-modules-extra
      dockerfile: xss_scanner/Dockerfile
    volumes: ["./docker/karton.ini:/etc/karton/karton.ini", "${DOCKER_COMPOSE_ADDITIONAL_SHARED_DIRECTORY:-./shared}:/shared/"]
    env_file: .env
    restart: always
    command: "python3 -m artemis.modules.xss_scanner"



  autoreporter:
    volumes:
      - ./Artemis-modules-extra/extra_modules_config.py:/opt/extra_modules_config.py
      - ./Artemis-modules-extra/autoreporter_addons/dns_reaper/:/opt/artemis/reporting/modules/dns_reaper/
      - ./Artemis-modules-extra/autoreporter_addons/forti_vuln/:/opt/artemis/reporting/modules/forti_vuln/
      - ./Artemis-modules-extra/autoreporter_addons/sqlmap/:/opt/artemis/reporting/modules/sqlmap/
      - ./Artemis-modules-extra/autoreporter_addons/moodle_scanner/:/opt/artemis/reporting/modules/moodle_scanner/
      - ./Artemis-modules-extra/autoreporter_addons/ssl_checks/:/opt/artemis/reporting/modules/ssl_checks/
      - ./Artemis-modules-extra/autoreporter_addons/xss_scanner/:/opt/artemis/reporting/modules/xss_scanner/
